### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by HHoflittlefish777** [labring/sealfs#23]
At present, it still a very simple system, and our first plan is  committed to improve performance of disk IO and network . The construction of general file systems, the priority will be lower.See readme.md for the work of the first version. Welcome to pay attention.
 - Client:
    - [x] fuse file system interface
    - [x] System call hijacking(file system of user mode)(doing)
    - [x] location  algorithm(need optimize)
    - [ ] batch process 
  - Sever:
    - [x] bypass  file system
    - [x] file Storage
    - [x] disk manager
    - [x] catalogue manager
    - [ ] Metadata persistent memory storage
    - [x] file index
    - [ ] file lock
    - [x] Persistent data structure   
  - Manger:
    - [x] heart manager(need optimize)
  - Network:
    - [ ] RDMA
    - [x] socket network 
  - Test
    - [x] IO500
    - [ ] function test
